# See https://doc.mergify.io
queue_rules:
  - name: default
    speculative_checks: 2
    conditions:
      - -files=.mergify.yml
      - or:
        - status-success=Quality Gate

pull_request_riles:
  - name: automatic merge
    actions:
      comment:
        message: Thanks for your contribution! Your pull request will be merged automatically so please do NOT manually merge it.
      queue:
        name: default
        method: squash
        commit_message_template: |-
          {{ title }} (#{{ number }})
          {{ body }}
    conditions:
      - -files=.mergify.yml
      - -label~=(do-not-merge)
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "#review-threads-unresolved=0"
      - check-success=Validate PR title
      - base=main
      - or:
        - status-success=Quality Gate