name: Pull Request Lint

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  validate:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: |-
            compiler
            grammar
            docs
          types: |-
            feat
            fix
            docs
            chore
            revert
            build
          subjectPattern: ^[^:]+$
          subjectPatternError: pr title should match pattern "type(scope)':' subject"
          requireScope: false
          
